#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path, PurePosixPath

if not __package__:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.build_public_release import PUBLIC_FILE_PATHS

ROOT = Path(__file__).resolve().parents[1]
DOCKERIGNORE = ROOT / ".dockerignore"

ROOT_INPUTS = frozenset(
    {
        "LICENSE.txt",
        "README.md",
        "pyproject.toml",
        "requirements-build.lock",
        "requirements-runtime.lock",
    }
)
RUNTIME_PREFIXES = (
    "brand/",
    "config/",
    "content/",
    "data/",
    "site/",
    "src/",
)
RUNTIME_ARTIFACTS = frozenset(
    {
        "artifacts/launch/remedialhq-launch-short-visual-prototype.mp4",
        "artifacts/launch/short-001-storyboard.json",
    }
)


def docker_input_files() -> tuple[str, ...]:
    candidates = ROOT_INPUTS | RUNTIME_ARTIFACTS | {
        value
        for value in PUBLIC_FILE_PATHS
        if value.startswith(RUNTIME_PREFIXES)
    }
    missing = sorted(value for value in candidates if not (ROOT / value).is_file())
    if missing:
        raise FileNotFoundError(f"allowlisted Docker inputs are missing: {missing}")
    return tuple(sorted(candidates))


def render_dockerignore() -> str:
    directories: set[str] = set()
    files = docker_input_files()
    for value in files:
        relative = PurePosixPath(value)
        for index in range(1, len(relative.parts)):
            directories.add("/".join(relative.parts[:index]) + "/")

    lines = [
        "# Generated by scripts/render_dockerignore.py. Deny everything by default.",
        "**",
        "!.dockerignore",
        "!Dockerfile",
    ]
    lines.extend(f"!{value}" for value in sorted(directories))
    lines.extend(f"!{value}" for value in files)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the exact Docker build allowlist")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if .dockerignore differs from the rendered allowlist",
    )
    args = parser.parse_args()
    rendered = render_dockerignore()
    if args.check:
        if not DOCKERIGNORE.is_file() or DOCKERIGNORE.read_text(encoding="utf-8") != rendered:
            raise SystemExit(".dockerignore is stale; run scripts/render_dockerignore.py")
        return 0
    DOCKERIGNORE.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
